"use client";
import {createContext,useContext,useEffect,useState} from "react";
export const translations:Record<string,Record<string,string>>={
en:{overview:"Overview",pantry:"My pantry",map:"Rescue map",pickups:"Pickups",recipes:"Recipe rescue",impact:"Community impact",search:"Search food, donations, recipes…",morning:"Good morning",attention:"Here’s what needs your attention today.",rescue:"Rescue food",mission:"TODAY’S RESCUE MISSION",save:"Save it before it’s wasted.",review:"Review expiring food",findRecipe:"Find a recipe",useSoon:"Use soon",near:"Rescue near you"},
ur:{overview:"جائزہ",pantry:"میری پینٹری",map:"ریسکیو نقشہ",pickups:"پک اپس",recipes:"ریسکیو تراکیب",impact:"کمیونٹی اثر",search:"کھانا، عطیات یا تراکیب تلاش کریں…",morning:"صبح بخیر",attention:"آج آپ کی توجہ کی ضرورت یہ ہے۔",rescue:"کھانا بچائیں",mission:"آج کا ریسکیو مشن",save:"ضائع ہونے سے پہلے بچائیں۔",review:"جلد ختم ہونے والا کھانا دیکھیں",findRecipe:"ترکیب تلاش کریں",useSoon:"جلد استعمال کریں",near:"آپ کے قریب ریسکیو"},
pa:{overview:"ਸੰਖੇਪ",pantry:"ਮੇਰੀ ਪੈਂਟਰੀ",map:"ਬਚਾਅ ਨਕਸ਼ਾ",pickups:"ਪਿਕਅੱਪ",recipes:"ਭੋਜਨ ਬਚਾਅ ਵਿਅੰਜਨ",impact:"ਕਮਿਊਨਿਟੀ ਪ੍ਰਭਾਵ",search:"ਭੋਜਨ, ਦਾਨ ਜਾਂ ਵਿਅੰਜਨ ਲੱਭੋ…",morning:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ",attention:"ਅੱਜ ਇਨ੍ਹਾਂ ਚੀਜ਼ਾਂ ਵੱਲ ਧਿਆਨ ਦਿਓ।",rescue:"ਭੋਜਨ ਬਚਾਓ",mission:"ਅੱਜ ਦਾ ਬਚਾਅ ਮਿਸ਼ਨ",save:"ਬਰਬਾਦ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਬਚਾਓ।",review:"ਜਲਦੀ ਖਰਾਬ ਹੋਣ ਵਾਲਾ ਭੋਜਨ ਵੇਖੋ",findRecipe:"ਵਿਅੰਜਨ ਲੱਭੋ",useSoon:"ਜਲਦੀ ਵਰਤੋ",near:"ਨੇੜੇ ਭੋਜਨ ਬਚਾਅ"},
sd:{overview:"جائزو",pantry:"منهنجي پينٽري",map:"بچاءَ جو نقشو",pickups:"پڪ اپ",recipes:"بچاءَ جون ترڪيبون",impact:"برادري جو اثر",search:"کاڌو، عطيو يا ترڪيب ڳوليو…",morning:"صبح جو سلام",attention:"اڄ هنن شين تي ڌيان ڏيو۔",rescue:"کاڌو بچايو",mission:"اڄ جو بچاءَ مشن",save:"ضايع ٿيڻ کان اڳ بچايو۔",review:"جلد ختم ٿيندڙ کاڌو ڏسو",findRecipe:"ترڪيب ڳوليو",useSoon:"جلد استعمال ڪريو",near:"ويجهو کاڌو بچاءَ"},
ps:{overview:"لنډیز",pantry:"زما خوراکي زېرمه",map:"د ژغورنې نقشه",pickups:"راټولونه",recipes:"د ژغورنې خواړه",impact:"ټولنیز اغېز",search:"خواړه، مرسته یا ترکیب ولټوئ…",morning:"سهار مو پخیر",attention:"نن دې شیانو ته پاملرنه وکړئ.",rescue:"خواړه وژغورئ",mission:"د نن ژغورنې ماموریت",save:"له ضایع کېدو مخکې یې وژغورئ.",review:"ژر ختمېدونکي خواړه وګورئ",findRecipe:"ترکیب ومومئ",useSoon:"ژر یې وکاروئ",near:"نږدې ژغورنه"},
ar:{overview:"نظرة عامة",pantry:"مخزوني",map:"خريطة الإنقاذ",pickups:"الاستلام",recipes:"وصفات الإنقاذ",impact:"أثر المجتمع",search:"ابحث عن طعام أو تبرعات أو وصفات…",morning:"صباح الخير",attention:"إليك ما يحتاج انتباهك اليوم.",rescue:"أنقذ الطعام",mission:"مهمة الإنقاذ اليوم",save:"أنقذه قبل أن يُهدر.",review:"راجع الطعام القريب من الانتهاء",findRecipe:"ابحث عن وصفة",useSoon:"استخدم قريباً",near:"إنقاذ بالقرب منك"},
es:{overview:"Resumen",pantry:"Mi despensa",map:"Mapa de rescate",pickups:"Recogidas",recipes:"Recetas de rescate",impact:"Impacto comunitario",search:"Buscar comida, donaciones o recetas…",morning:"Buenos días",attention:"Esto necesita tu atención hoy.",rescue:"Rescatar comida",mission:"MISIÓN DE RESCATE DE HOY",save:"Sálvala antes de desperdiciarla.",review:"Revisar alimentos",findRecipe:"Buscar receta",useSoon:"Usar pronto",near:"Rescate cerca de ti"},
fr:{overview:"Aperçu",pantry:"Mon garde-manger",map:"Carte de sauvetage",pickups:"Collectes",recipes:"Recettes anti-gaspi",impact:"Impact communautaire",search:"Rechercher aliments, dons ou recettes…",morning:"Bonjour",attention:"Voici ce qui demande votre attention aujourd’hui.",rescue:"Sauver des aliments",mission:"MISSION DU JOUR",save:"Sauvez-les avant le gaspillage.",review:"Voir les aliments urgents",findRecipe:"Trouver une recette",useSoon:"À utiliser bientôt",near:"Sauvetages proches"}
};
type TranslateWindow=Window&{google?:{translate:{TranslateElement:new(options:{pageLanguage:string;includedLanguages:string;autoDisplay:boolean},id:string)=>unknown}};googleTranslateElementInit?:()=>void};
type Ctx={theme:string;toggleTheme:()=>void;location:string;setLocation:(x:string)=>void;lang:string;setLang:(x:string)=>void;t:(x:string)=>string};
const AppContext=createContext<Ctx|null>(null);
export function AppProvider({children}:{children:React.ReactNode}){const [theme,setTheme]=useState(()=>typeof window!=="undefined"?localStorage.getItem("resq-theme")||"light":"light");const [location,setLocation]=useState("Karachi, Pakistan");const [lang,setLanguage]=useState(()=>typeof window!=="undefined"?localStorage.getItem("resq-language")||"en":"en");const t=(key:string)=>translations[lang]?.[key]||translations.en[key]||key;useEffect(()=>{const w=window as TranslateWindow;const initialize=()=>{if(!w.google||document.getElementById("google_translate_element")?.hasChildNodes())return;new w.google.translate.TranslateElement({pageLanguage:"en",includedLanguages:"en,ur,pa,sd,ps,ar,es,fr",autoDisplay:false},"google_translate_element")};w.googleTranslateElementInit=initialize;if(w.google)initialize();else if(!document.getElementById("google-translate-script")){const script=document.createElement("script");script.id="google-translate-script";script.src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit";script.async=true;document.head.appendChild(script)}},[]);useEffect(()=>{localStorage.setItem("resq-language",lang);document.documentElement.lang=lang;document.documentElement.dir=["ur","sd","ps","ar"].includes(lang)?"rtl":"ltr";let attempts=0;const timer=window.setInterval(()=>{const combo=document.querySelector<HTMLSelectElement>(".goog-te-combo");if(combo){if(combo.value!==lang){combo.value=lang;combo.dispatchEvent(new Event("change",{bubbles:true}))}window.clearInterval(timer)}else if(++attempts>20)window.clearInterval(timer)},250);return()=>window.clearInterval(timer)},[lang]);const setLang=(value:string)=>setLanguage(value);const toggleTheme=()=>setTheme(v=>{const n=v==="light"?"dark":"light";localStorage.setItem("resq-theme",n);return n});return <AppContext.Provider value={{theme,toggleTheme,location,setLocation,lang,setLang,t}}><div id="google_translate_element" aria-hidden="true"/>{children}</AppContext.Provider>}
export const useApp=()=>{const c=useContext(AppContext);if(!c)throw new Error("useApp must be inside AppProvider");return c};
