"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Provider, useDispatch, useSelector } from "react-redux";
import Image from "next/image";
import { BrowserMultiFormatReader, type IScannerControls } from "@zxing/browser";
import { AppProvider, useApp } from "./state/AppContext";
import { store, type AppDispatch, type RootState } from "./state/store";
import { addInventory, removeInventory } from "./state/inventorySlice";
import { claimDonation, loadNearbyDonations, postDonation } from "./state/donationsSlice";
import { createRequest, updateRequest } from "./state/requestsSlice";
import { fetchRecipes } from "./state/recipesSlice";
import { dijkstra, type WeightedGraph } from "./lib/shortestPath";

const nav = [
  ["overview", "overview", "⌂"], ["inventory", "pantry", "▤"],
  ["donations", "map", "⌖"], ["requests", "pickups", "↗"],
  ["recipes", "recipes", "✦"], ["impact", "impact", "◒"],
];

function Shell() {
  const [page, setPage] = useState("overview");
  const [menu, setMenu] = useState(false);
  const { theme, toggleTheme, location, lang, setLang, t } = useApp();
  const [locationOpen,setLocationOpen]=useState(false);
  const [notificationsOpen,setNotificationsOpen]=useState(false);
  const inventory = useSelector((s: RootState) => s.inventory.items);
  const donations = useSelector((s: RootState) => s.donations.items);
  const requests = useSelector((s: RootState) => s.requests.items);
  const expiring = inventory.filter(i => i.days <= 3).length;
  const content: Record<string, React.ReactNode> = {
    overview: <Overview go={setPage} expiring={expiring} donations={donations.length} requests={requests.length} />,
    inventory: <Inventory />,
    donations: <Donations />,
    requests: <Requests />,
    recipes: <Recipes />,
    impact: <Impact />,
  };
  return <div className={theme === "dark" ? "app dark" : "app"}>
    <aside className={menu ? "sidebar open" : "sidebar"}>
      <button className="close" onClick={() => setMenu(false)}>×</button>
      <div className="brand"><Image className="brandmark" src="/resqplate-logo.svg" alt="ResQPlate" width={38} height={38} priority/><div><b>ResQPlate</b><small>Food worth saving</small></div></div>
      <div className="impact-mini"><span>COMMUNITY IMPACT</span><strong>1,284 <small>meals rescued</small></strong><div><i style={{width:"72%"}} /></div></div>
      <nav>{nav.map(([id,label,icon]) => <button key={id} className={page===id?"active":""} onClick={()=>{setPage(id);setMenu(false)}}><span>{icon}</span>{t(label)}{id==="inventory"&&expiring>0?<em>{expiring}</em>:null}</button>)}</nav>
    </aside>
    <main className="main">
      <header><button className="hamburger" onClick={()=>setMenu(true)}>☰</button><div className="search">⌕ <input aria-label="Search" placeholder={t("search")} /></div><button className="location-btn" onClick={()=>setLocationOpen(true)}>⌖ <span>{location}</span></button><select className="language" aria-label="Language" value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="ur">اردو</option><option value="pa">ਪੰਜਾਬੀ</option><option value="sd">سنڌي</option><option value="ps">پښتو</option><option value="ar">العربية</option><option value="es">Español</option><option value="fr">Français</option></select><button className="iconbtn notification-btn" aria-label="Expiry notifications" aria-expanded={notificationsOpen} onClick={()=>setNotificationsOpen(v=>!v)}>♢<span className="dot"/></button><button className="iconbtn" aria-label="Switch theme" onClick={toggleTheme}>{theme==="dark"?"☀":"◐"}</button>{notificationsOpen&&<NotificationPanel items={inventory} close={()=>setNotificationsOpen(false)} go={setPage}/>}</header>
      <div className="content">{content[page]}</div>
    </main>
    {locationOpen&&<LocationFinder close={()=>setLocationOpen(false)}/>}<RescueCursor/>
  </div>
}

function Overview({go,expiring,donations,requests}:{go:(p:string)=>void,expiring:number,donations:number,requests:number}) {
  const {t,location}=useApp();
  const inventory=useSelector((s:RootState)=>s.inventory.items);
  const total=inventory.reduce((a,b)=>a+b.quantity,0);
  return <>
    <div className="welcome"><div><span className="eyebrow">LIVE IN {location.toUpperCase()}</span><h1>{t("morning")}</h1><p>{t("attention")}</p></div><button className="primary" onClick={()=>go("donations")}>＋ {t("rescue")}</button></div>
    <StoryCarousel go={go} expiring={expiring}/>
    <div className="stats"><Stat icon="▤" value={total} label="Items in pantry" note={`${expiring} need attention`} tone="orange"/><Stat icon="♡" value={donations} label="Nearby rescues" note="Within 5 km" tone="green"/><Stat icon="↗" value={requests} label="Active pickups" note="Community coordinated" tone="blue"/><Stat icon="◒" value="8.6 kg" label="Waste prevented" note="+18% this month" tone="purple"/></div>
    <div className="grid-two"><section className="panel"><PanelTitle title={t("useSoon")} sub="Items closest to expiry" action="View pantry" onClick={()=>go("inventory")}/><div className="food-list">{inventory.slice(0,3).map(i=><div className="food-row" key={i.id}><span className={`food-icon ${i.color}`}>{i.emoji}</span><div><b>{i.name}</b><small>{i.quantity} {i.unit} · {i.category}</small></div><strong className={i.days<=1?"urgent":"soon"}>{i.days<=0?"Today":i.days===1?"Tomorrow":`${i.days} days`}</strong></div>)}</div></section>
      <section className="panel"><PanelTitle title={t("near")} sub={`Fresh listings around ${location}`} action="Open map" onClick={()=>go("donations")}/><GlobalMap compact/></section></div>
    <section className="how"><div><span className="eyebrow">ONE PLATE AT A TIME</span><h2>Rescue food in three simple steps</h2></div><div className="steps"><Step n="01" title="Spot it" text="Track expiry dates or find safe surplus nearby."/><Step n="02" title="Share it" text="Post a donation or request a community pickup."/><Step n="03" title="Save it" text="Cook, collect, and record your rescued impact."/></div></section>
  </>
}
function Stat({icon,value,label,note,tone}:{icon:string,value:string|number,label:string,note:string,tone:string}){return <div className="stat"><span className={`stat-icon ${tone}`}>{icon}</span><div><strong>{value}</strong><b>{label}</b><small>{note}</small></div></div>}
function PanelTitle({title,sub,action,onClick}:{title:string,sub:string,action:string,onClick:()=>void}){return <div className="panel-title"><div><h3>{title}</h3><p>{sub}</p></div><button onClick={onClick}>{action} →</button></div>}
function Step({n,title,text}:{n:string,title:string,text:string}){return <div className="step"><span>{n}</span><div><b>{title}</b><p>{text}</p></div></div>}

function NotificationPanel({items,close,go}:{items:Array<{id:string;name:string;days:number;emoji:string}>,close:()=>void,go:(p:string)=>void}){const urgent=items.filter(x=>x.days<=3);return <aside className="notification-panel"><div className="notification-head"><div><span className="eyebrow">USE-SOON ALERTS</span><h3>{urgent.length} items need attention</h3></div><button onClick={close}>×</button></div><div className="notification-list">{urgent.map(x=><div key={x.id}><span>{x.emoji}</span><div><b>{x.name}</b><small>{x.days<=0?"Expires today":x.days===1?"Expires tomorrow":`Expires in ${x.days} days`}</small></div><em className={x.days<=1?"urgent":"soon"}>{x.days<=1?"Urgent":"Soon"}</em></div>)}</div><button className="notification-action" onClick={()=>{go("inventory");close()}}>Review my pantry →</button></aside>}

function StoryCarousel({go,expiring}:{go:(p:string)=>void,expiring:number}){const {t}=useApp();const [slide,setSlide]=useState(0);useEffect(()=>{const id=setInterval(()=>setSlide(s=>(s+1)%3),5000);return()=>clearInterval(id)},[]);const stories=[{tag:t("mission"),title:t("save"),text:`You have ${expiring} items expiring soon. Cook them, share them, or donate safely.`,button:t("review"),page:"inventory",image:"/images/resqplate-hero.png"},{tag:"NEIGHBOURS HELPING NEIGHBOURS",title:"Food rescue feels better together.",text:"Discover surplus meals and coordinate a respectful pickup in your own city.",button:"Explore nearby rescues",page:"donations",image:"/images/resqplate-donation.png"},{tag:"COOK WHAT YOU HAVE",title:"Turn ‘use soon’ into tonight’s favourite.",text:"Match expiring ingredients with flexible, waste-smart recipe ideas.",button:t("findRecipe"),page:"recipes",image:"/images/resqplate-recipe.png"}];const s=stories[slide];return <section className="hero-card photo-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(6,49,37,.94),rgba(8,59,44,.64),rgba(8,59,44,.12)),url(${s.image})`}}><div><span className="tag">{s.tag}</span><h2>{s.title}</h2><p>{s.text}</p><div className="hero-actions"><button onClick={()=>go(s.page)}>{s.button} →</button></div></div><div className="carousel-dots">{stories.map((_,i)=><button aria-label={`Story ${i+1}`} className={i===slide?"on":""} onClick={()=>setSlide(i)} key={i}/>)}</div></section>}

function GlobalMap({compact=false,destination}:{compact?:boolean;destination?:string}){const {location}=useApp();const q=encodeURIComponent(`${location} food rescue`);const route=destination?`https://www.google.com/maps?output=embed&saddr=${encodeURIComponent(location)}&daddr=${encodeURIComponent(destination)}`:`https://www.google.com/maps?q=${q}&output=embed`;const external=destination?`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(location)}&destination=${encodeURIComponent(destination)}`:`https://www.google.com/maps/search/?api=1&query=${q}`;return <div className={compact?"map-embed compact":"map-embed"}><iframe title={destination?`Shortest route from ${location} to ${destination}`:`Food rescue map for ${location}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={route}/><a href={external} target="_blank" rel="noreferrer">{destination?"Open route in Google Maps":"Open in Google Maps"} ↗</a></div>}

function LocationFinder({close}:{close:()=>void}){const {location,setLocation}=useApp();const [q,setQ]=useState(location);const [results,setResults]=useState<Array<{display_name:string;lat:string;lon:string}>>([]);const [loading,setLoading]=useState(false);const search=async()=>{if(q.trim().length<2)return;setLoading(true);try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&limit=8&q=${encodeURIComponent(q)}`,{headers:{"Accept-Language":"en"}});setResults(await r.json())}finally{setLoading(false)}};return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="location-modal"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">WORLDWIDE DISCOVERY</span><h2>Where are you rescuing food?</h2><p>Search any country, city, town, district, or neighbourhood in the world.</p><div className="location-search"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="e.g. Barcelona, Spain"/><button onClick={search}>{loading?"Searching…":"Search world"}</button></div><button className="detect" onClick={()=>navigator.geolocation?.getCurrentPosition(async p=>{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${p.coords.latitude}&lon=${p.coords.longitude}`);const d=await r.json();setLocation(d.display_name||`${p.coords.latitude}, ${p.coords.longitude}`);close()})}>◎ Use my live location</button><div className="location-results">{results.map(x=><button key={`${x.lat}-${x.lon}`} onClick={()=>{setLocation(x.display_name);close()}}><span>⌖</span><div><b>{x.display_name.split(",")[0]}</b><small>{x.display_name}</small></div><em>Choose</em></button>)}</div><small className="privacy">Location is used to personalise nearby rescue discovery. You stay in control.</small></section></div>}

function RescueCursor(){useEffect(()=>{if(matchMedia("(pointer: coarse)").matches)return;const halo=document.createElement("div"),dot=document.createElement("div");halo.className="rescue-cursor";dot.className="rescue-dot";document.body.append(halo,dot);const move=(e:MouseEvent)=>{const position=`translate3d(${e.clientX}px,${e.clientY}px,0)`;dot.style.transform=position;halo.style.transform=position};window.addEventListener("mousemove",move,{passive:true});return()=>{window.removeEventListener("mousemove",move);halo.remove();dot.remove()}},[]);return null}

function Inventory(){
 const dispatch=useDispatch<AppDispatch>(); const items=useSelector((s:RootState)=>s.inventory.items); const [name,setName]=useState(""); const [days,setDays]=useState(3);const [scanner,setScanner]=useState(false);
 return <Page title="My pantry" sub="Track what you have. Waste less of what you buy." badge={`${items.filter(i=>i.days<=3).length} need attention`}><div className="toolbar"><div className="scan-box pantry-banner"><div><b>Scan it. Store it. Save it.</b><small>Use your camera or enter a barcode to find the real product in Open Food Facts.</small></div><button onClick={()=>setScanner(true)}>Scan barcode</button></div></div><div className="split"><section className="panel"><h3>Add an item</h3><div className="form-grid"><label>Food name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Spinach"/></label><label>Expires in<select value={days} onChange={e=>setDays(+e.target.value)}><option value="0">Today</option><option value="1">Tomorrow</option><option value="3">3 days</option><option value="7">7 days</option></select></label><button className="primary" onClick={()=>{if(name.trim()){dispatch(addInventory({name:name.trim(),days}));setName("")}}}>＋ Add to pantry</button></div></section><section className="panel inventory-list"><h3>Your food <small>{items.length} items</small></h3>{items.map(i=><div className="inv-card" key={i.id}><span className={`food-icon ${i.color}`}>{i.emoji}</span><div><b>{i.name}</b><small>{i.quantity} {i.unit} · Added recently</small></div><span className={i.days<=1?"pill urgent":"pill soon"}>{i.days<=0?"Use today":`${i.days} days left`}</span><button onClick={()=>dispatch(removeInventory(i.id))}>×</button></div>)}</section></div>{scanner&&<BarcodeScanner close={()=>setScanner(false)} add={(product)=>{dispatch(addInventory({name:product,days:7}));setScanner(false)}}/>}</Page>
}

function BarcodeScanner({close,add}:{close:()=>void;add:(name:string)=>void}){const videoRef=useRef<HTMLVideoElement>(null);const controlsRef=useRef<IScannerControls|null>(null);const [barcode,setBarcode]=useState("");const [status,setStatus]=useState("Choose camera scanning or enter the number printed below the barcode.");const [loading,setLoading]=useState(false);const stopCamera=()=>{controlsRef.current?.stop();controlsRef.current=null;if(videoRef.current?.srcObject)(videoRef.current.srcObject as MediaStream).getTracks().forEach(track=>track.stop())};useEffect(()=>stopCamera,[]);const lookup=async(code=barcode)=>{const clean=code.replace(/\D/g,"");if(clean.length<8){setStatus("Enter a valid barcode containing at least 8 digits.");return}setLoading(true);setStatus("Searching Open Food Facts…");try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${clean}.json`);const d=await r.json();if(d.status===1&&d.product){const name=d.product.product_name_en||d.product.product_name||d.product.generic_name||`Product ${clean}`;setStatus(`Found: ${name}`);add(name)}else setStatus("Product not found. Check the digits or add the item manually.")}catch{setStatus("Product lookup is unavailable right now. Please try again.")}finally{setLoading(false)}};const startCamera=async()=>{if(!navigator.mediaDevices?.getUserMedia||!videoRef.current){setStatus("Camera access is unavailable. Use manual barcode entry below.");return}try{stopCamera();setStatus("Starting camera…");const reader=new BrowserMultiFormatReader();controlsRef.current=await reader.decodeFromVideoDevice(undefined,videoRef.current,(result)=>{if(!result)return;const code=result.getText();setBarcode(code);stopCamera();void lookup(code)});setStatus("Point the camera at the barcode and hold it steady.")}catch{setStatus("Camera permission was denied or no camera was found. Manual barcode entry still works.")}};return <div className="modal-backdrop"><section className="scanner-modal"><button className="modal-close" onClick={()=>{stopCamera();close()}}>×</button><span className="eyebrow">REAL PRODUCT LOOKUP</span><h2>Scan a food barcode</h2><p>Cross-browser scanning supports EAN, UPC, Code 128 and other common product formats.</p><div className="scanner-view"><video ref={videoRef} muted playsInline/><div className="scan-line"/><span>Keep the barcode inside the frame</span></div><button className="camera-button" onClick={startCamera}>▦ Start camera scanner</button><div className="barcode-entry"><label>Barcode number<input inputMode="numeric" value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder="e.g. 3017620422003"/></label><button disabled={loading} onClick={()=>lookup()}>{loading?"Searching…":"Find product"}</button></div><p className="scanner-status" role="status">{status}</p><small className="scanner-note">Product data comes from the public Open Food Facts catalogue.</small></section></div>}
function Donations(){
 const dispatch=useDispatch<AppDispatch>(); const {items,status}=useSelector((s:RootState)=>s.donations); const [show,setShow]=useState(false);
 const {location}=useApp();const [routeDestination,setRouteDestination]=useState("Green Table Café");return <Page title="Rescue map" sub={`Discover food and calculate the most efficient pickup path near ${location}.`} badge="Smart route planning"><div className="toolbar"><button className="primary" onClick={()=>setShow(!show)}>＋ Post surplus</button><button className="secondary" onClick={()=>dispatch(loadNearbyDonations())}>{status==="loading"?"Locating…":"⌖ Refresh nearby"}</button></div>{show&&<div className="quick-form"><b>Share food safely</b><p>Add collection timing, allergens, storage conditions, and a clear handover point.</p><button onClick={()=>{dispatch(postDonation());setShow(false)}}>Post 6 bakery portions</button></div>}<RouteOptimizer goal={routeDestination} setGoal={setRouteDestination}/><div className="donation-layout"><GlobalMap destination={`${routeDestination}, ${location}`}/><div className="cards">{items.map(d=><article className="donation" key={d.id}><div className={`donation-photo ${d.photo}`} style={{backgroundImage:`url(/images/resqplate-donation.png)`}}><em>{d.distance}</em></div><div><span className="tag">{d.type}</span><h3>{d.title}</h3><p>{d.place} · {d.time}</p><div className="donor"><span>{d.initial}</span><small><b>{d.donor}</b><br/>Safety details provided</small></div><div className="donation-actions"><button disabled={!d.available} onClick={()=>dispatch(claimDonation(d.id))}>{d.available?"Request pickup":"Requested ✓"}</button><a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${d.place}, ${location}`)}`} target="_blank" rel="noreferrer">Directions ↗</a></div></div></article>)}</div></div></Page>
}

function RouteOptimizer({goal,setGoal}:{goal:string;setGoal:(x:string)=>void}){const base:WeightedGraph={"Your location":{"Community Hub":1.2,"Clifton Bakehouse":2.8,"City Food Bank":4.4},"Community Hub":{"Your location":1.2,"Clifton Bakehouse":.9,"Green Table Café":1.7,"Student Meal Point":2.3},"Clifton Bakehouse":{"Your location":2.8,"Community Hub":.9,"Green Table Café":1.1,"Neighbourhood Share":2.2},"Green Table Café":{"Community Hub":1.7,"Clifton Bakehouse":1.1,"Neighbourhood Share":1.3,"City Food Bank":2.1},"Neighbourhood Share":{"Clifton Bakehouse":2.2,"Green Table Café":1.3,"Student Meal Point":1.5},"City Food Bank":{"Your location":4.4,"Green Table Café":2.1,"Student Meal Point":1.2},"Student Meal Point":{"Community Hub":2.3,"Neighbourhood Share":1.5,"City Food Bank":1.2}};const [graph,setGraph]=useState<WeightedGraph>(base);const [adding,setAdding]=useState(false);const [custom,setCustom]=useState("");const [distance,setDistance]=useState("3");const destinations=Object.keys(graph).filter(x=>x!=="Your location"&&x!=="Community Hub");const route=dijkstra(graph,"Your location",goal);const modes=[{icon:"🚶",name:"Walk",speed:5},{icon:"🚲",name:"Bicycle",speed:15},{icon:"🛵",name:"Scooter",speed:25},{icon:"🚗",name:"Car",speed:35}];const addDestination=()=>{const name=custom.trim(),km=Number(distance);if(!name||!Number.isFinite(km)||km<=0)return;setGraph(g=>({...g,"Your location":{...g["Your location"],[name]:km},[name]:{"Your location":km}}));setGoal(name);setCustom("");setAdding(false)};return <section className="route-optimizer"><div className="route-copy"><span className="route-symbol">⌁</span><div><span className="eyebrow">SHORTEST-PATH RESCUE PLANNER</span><h3>See the fastest way to reach food.</h3><p>Choose a saved pickup or add any destination. Dijkstra’s algorithm finds the lowest-distance graph route and the map displays it.</p></div></div><div className="route-controls"><div className="destination-row"><label>Pickup destination<select value={goal} onChange={e=>setGoal(e.target.value)}>{destinations.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>setAdding(v=>!v)}>＋ Add destination</button></div>{adding&&<div className="custom-destination"><input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Pickup name or address"/><input value={distance} onChange={e=>setDistance(e.target.value)} inputMode="decimal" placeholder="Distance in km"/><button onClick={addDestination}>Add to route graph</button></div>}<div className="route-result"><span>{route.path.map((node,i)=><span key={node}><b>{node}</b>{i<route.path.length-1?<i>→</i>:null}</span>)}</span><strong>{route.distance.toFixed(1)} km<small>shortest calculated path</small></strong></div><div className="travel-times">{modes.map(m=>{const mins=Math.max(1,Math.round(route.distance/m.speed*60));return <div key={m.name}><span>{m.icon}</span><b>{m.name}</b><strong>{mins} min</strong><small>est. at {m.speed} km/h</small></div>})}</div></div></section>}
function Requests(){const dispatch=useDispatch<AppDispatch>();const items=useSelector((s:RootState)=>s.requests.items);return <Page title="Pickup requests" sub="Coordinate collections clearly, respectfully, and on time." badge={`${items.filter(x=>x.status!=="Completed").length} active`}><section className="pickup-banner"><div><span className="eyebrow">COLLECT WITH CONFIDENCE</span><h2>Every handover, clearly coordinated.</h2><p>Keep addresses, time windows, food details, and collection status together from request to rescue.</p></div></section><div className="request-board">{["Requested","Confirmed","Completed"].map(status=><section className="kanban" key={status}><div className="kanban-head"><b>{status}</b><span>{items.filter(x=>x.status===status).length}</span></div>{items.filter(x=>x.status===status).map(r=><article key={r.id}><span className="tag">{r.kind}</span><h3>{r.title}</h3><p>⌖ {r.location}</p><p>◷ {r.time}</p><div><span className="avatar small">{r.initial}</span><b>{r.person}</b></div>{status!=="Completed"&&<button onClick={()=>dispatch(updateRequest(r.id))}>{status==="Requested"?"Confirm pickup":"Mark collected"} →</button>}</article>)}{status==="Requested"&&<button className="add-card" onClick={()=>dispatch(createRequest())}>＋ Add pickup request</button>}</section>)}</div></Page>}
function Recipes(){const dispatch=useDispatch<AppDispatch>();const {items,status}=useSelector((s:RootState)=>s.recipes);const pantry=useSelector((s:RootState)=>s.inventory.items);const ingredients=useMemo(()=>pantry.filter(x=>x.days<=3).map(x=>x.name).join(", "),[pantry]);return <Page title="Recipe rescue" sub="Turn food that needs attention into something worth sharing." badge="Waste-smart ideas"><section className="recipe-hero"><div><span className="tag">SMART MATCH</span><h2>Cook with what’s expiring.</h2><p>We found ingredients that need attention: <b>{ingredients}</b>.</p><button onClick={()=>dispatch(fetchRecipes(ingredients))}>{status==="loading"?"Creating ideas…":"Find recipe ideas"}</button></div></section><div className="recipe-grid">{items.map(r=><article key={r.id}><div className={`recipe-photo ${r.color}`}><em>{r.match}% pantry match</em></div><div><small>{r.time} · {r.level}</small><h3>{r.title}</h3><p>{r.description}</p><div>{r.ingredients.map(x=><span className="ingredient" key={x}>{x}</span>)}</div><button>View rescue recipe →</button></div></article>)}</div></Page>}
function Impact(){return <Page title="Community impact" sub="See every saved plate turn into measurable local progress." badge="Growing together"><section className="impact-hero"><div><span className="eyebrow">GLOBAL RESCUE COLLECTIVE</span><h2>Small rescues.<br/>Planet-sized impact.</h2><p>Every pantry item used, surplus box shared, and pickup completed strengthens the local food loop.</p><button>Invite your community →</button></div><div className="impact-orbit"><strong>8.6<small>kg saved</small></strong></div></section><div className="impact-grid"><article><strong>1,284</strong><b>Meals rescued</b><p>Enough food for a full school week.</p></article><article><strong>312 kg</strong><b>CO₂e avoided</b><p>Estimated environmental benefit.</p></article><article><strong>428</strong><b>Neighbour connections</b><p>Food shared with dignity nearby.</p></article><article><strong>36</strong><b>Local partners</b><p>Cafés, shops, and community groups.</p></article></div><section className="panel challenge"><span>WEEKLY COMMUNITY CHALLENGE</span><h2>Rescue 500 breakfasts before Sunday</h2><div><i style={{width:"68%"}}/></div><p><b>341 meals saved</b><em>159 to go</em></p></section></Page>}
function Page({title,sub,badge,children}:{title:string,sub:string,badge:string,children:React.ReactNode}){return <><div className="page-head"><div><span className="eyebrow">RESQPLATE WORKSPACE</span><h1>{title}</h1><p>{sub}</p></div><span className="status-badge">● {badge}</span></div>{children}</>}
export default function Home(){return <Provider store={store}><AppProvider><Shell/></AppProvider></Provider>}
